// version 1.5.x $Id: nb.js 150 2006-12-06 06:57:22Z jens $
// author Joomla! i Norge http://www.joomlainorge.no oversettelser@joomlainorge.no
// copyright Copyright (C) 2005 - 2008 Joomla! i Norge. All rights reserved.
// license http://www.gnu.org/copyleft/gpl.html GNU/GPL, see LICENSE.php

tinyMCE.addToLang('fullpage',{
	title : 'Dokumentegenskaper',
	desc : 'Dokumentegenskaper',
	meta_tab : 'Generelt',
	appearance_tab : 'Utseende',
	advanced_tab : 'Avansert',
	meta_props : 'Meta-informasjon',
	langprops : 'Spåk og encoding',
	meta_title : 'Titel',
	meta_keywords : 'Nøkkeord',
	meta_description : 'Beskrivelse',
	meta_robots : 'Robots',
	doctypes : 'Doctype',
	langcode : 'Språkkode',
	langdir : 'Språkretning',
	ltr : 'Venstre mot høyre',
	rtl : 'Høyre mot venstre',
	xml_pi : 'XML-deklarasjon',
	encoding : 'Tegnkode',
	appearance_bgprops : 'Bakgrunnsegenskaper',
	appearance_marginprops : 'Kroppmarginer',
	appearance_linkprops : 'Lenkefarger',
	appearance_textprops : 'Tekstegenskaper',
	bgcolor : 'Bakgrunnsfarge',
	bgimage : 'Bakgrunnsbilde',
	left_margin : 'Venstre margin',
	right_margin : 'Høyre margin',
	top_margin : 'Topp margin',
	bottom_margin : 'Bunn margin',
	text_color : 'Tekstfarge',
	font_size : 'Skriftstørrelse',
	font_face : 'Skriftutseende',
	link_color : 'Lenkefarge',
	hover_color : 'Hover-farge',
	visited_color : 'Besøkt farge',
	active_color : 'Aktiv farge',
	textcolor : 'Farge',
	fontsize : 'Skriftstørrelse',
	fontface : 'Skriftfamilie',
	meta_index_follow : 'Indekser og følge lenkene',
	meta_index_nofollow : 'Indekser men ikke følge lenkene',
	meta_noindex_follow : 'Ikke indekser men følg lenkene',
	meta_noindex_nofollow : 'Ikke indekser og ikke følge lenkene',
	appearance_style : 'Stilsett og stilvalg',
	stylesheet : 'Stilset',
	style : 'Stil',
	author : 'Skribent',
	copyright : 'Opphavsrett',
	add : 'Legg til element',
	remove : 'Fjern valgte element',
	moveup : 'Flytte valgte element opp',
	movedown : 'Flytte valgte element ned',
	head_elements : 'Hode-elementer',
	info : 'Informasjon',
	info_text : '',
	add_title : 'Tittel-element',
	add_meta : 'Meta-element',
	add_script : 'Skript-element',
	add_style : 'Stil-element',
	add_link : 'Lenke-element',
	add_base : 'Basis-element',
	add_comment : 'Kommentarnode',
	title_element : 'Tittel-element',
	script_element : 'Skript-element',
	style_element : 'Stil-element',
	base_element : 'Basis-element',
	link_element : 'Lenke-element',
	meta_element : 'Meta-element',
	comment_element : 'Kommentar',
	src : 'Kilde',
	language : 'Språk',
	href : 'Href',
	target : 'Mål',
	rel : 'Rel',
	type : 'Type',
	charset : 'Karaktersett',
	defer : 'Utsett',
	media : 'Media',
	properties : 'Innstillinger',
	name : 'Navn',
	value : 'Verdi',
	content : 'Innhold',
	rel : 'Rel',
	rev : 'Rev',
	hreflang : 'Href-språk',
	general_props : 'Generelt',
	advanced_props : 'Avansert',
	delta_width : 0,
	delta_height : 0
});
