// version 1.5.x $Id: nb.js 117 2006-10-24 12:49:07Z jens $
// author Joomla! i Norge http://www.joomlainorge.no oversettelser@joomlainorge.no
// copyright Copyright (C) 2005 - 2008 Joomla! i Norge. All rights reserved.
// license http://www.gnu.org/copyleft/gpl.html GNU/GPL, see LICENSE.php

tinyMCE.addToLang('advlink',{
general_tab : 'Generelle innstillinger',
popup_tab : 'Popup',
events_tab : 'Hendelser',
advanced_tab : 'Avanserte innstillinger',
general_props : 'Generelle innstillinger',
popup_props : 'Popup-innstillinger',
event_props : 'Hendelser',
advanced_props : 'Avanserte innstillinger',
popup_opts : 'Innstillinger',
anchor_names : 'Anker',
target_same : 'Åpne i samme vindu / ramme',
target_parent : 'Åpne i underliggende vindu / ramme',
target_top : 'Åpne i topprammen (erstatter alle rammer)',
target_blank : 'Åpne i et nytt vindu',
popup : 'Javascript-popup',
popup_url : 'Nettadresse til popup ',
popup_name : 'Vindunavn',
popup_return : 'Sett inn \'return false\'',
popup_scrollbars : 'Vis rullefelt',
popup_statusbar : 'Vis statuslinje',
popup_toolbar : 'Vis verktøylinje',
popup_menubar : 'Vis menylinje',
popup_location : 'Vis adressefelt',
popup_resizable : 'Gjør vinduet skalerbart',
popup_dependent : 'Avhengig vindu (Bare i Mozilla/Firefox)',
popup_size : 'Størrelse',
popup_position : 'Posisjon (X/Y)',
id : 'Id',
style: 'Stil',
classes : 'CSS-klasser',
target_name : 'Målnavn',
langdir : 'Skriftretning',
target_langcode : 'Målspråk',
langcode : 'Språkkode',
encoding : 'Tegnkonvertering',
mime : 'Målets MIME-type',
rel : 'Relasjonside til mål',
rev : 'Relasjonsmål til side',
tabindex : 'Tabindeks',
accesskey : 'Hurtigtast',
ltr : 'Venstre mot høyre',
rtl : 'Høyre mot venstre'
});
