// version 1.5.x $Id: nb.js 179 2007-02-14 19:24:38Z jens $
// author Joomla! i Norge http://www.joomlainorge.no oversettelser@joomlainorge.no
// copyright Copyright (C) 2005 - 2008 Joomla! i Norge. All rights reserved.
// license http://www.gnu.org/copyleft/gpl.html GNU/GPL, see LICENSE.php

tinyMCE.addToLang('style',{
title : 'Rediger CSS-stiler',
styleinfo_desc : 'Rediger CSS-stiler',
apply : 'Bruk',
text_tab : 'Tekst',
background_tab : 'Bakgrunn',
block_tab : 'Blokk',
box_tab : 'Boks',
border_tab : 'Rammer',
list_tab : 'Liste',
positioning_tab : 'Posisjonering',
text_props : 'Tekst',
text_font : 'Font',
text_size : 'Størrelse',
text_weight : 'Tyngde',
text_style : 'Stil',
text_variant : 'Variant',
text_lineheight : 'Linjehøyde',
text_case : 'Skriftstørrelse',
text_color : 'Farge',
text_decoration : 'Dekorasjon',
text_overline : 'overstreket',
text_underline : 'understreket',
text_striketrough : 'gjennomstreket',
text_blink : 'blink',
text_none : 'ikke noe',
background_color : 'Bakgrunnsfarge',
background_image : 'Bakgrunnsbilde',
background_repeat : 'Repeter',
background_attachment : 'Vedlegg',
background_hpos : 'Horisontal posisjon',
background_vpos : 'Vertikal posisjon',
block_wordspacing : 'Ordmellomrom',
block_letterspacing : 'Bokstavmellomrom',
block_vertical_alignment : 'Vertikal justering',
block_text_align : 'Tekstjustering',
block_text_indent : 'Tekstinnrykk',
block_whitespace : 'Hvitt mellomrom',
block_display : 'Vis',
box_width : 'Bredde',
box_height : 'Høyde',
box_float : 'Flyt',
box_clear : 'Fjerne',
padding : 'Utforing',
same : 'Likt for alle',
top : 'Topp',
right : 'Høyre',
bottom : 'Bunn',
left : 'Venstre',
margin : 'Rand',
style : 'Stil',
width : 'Bredde',
height : 'Høyde',
color : 'Farge',
list_type : 'Type',
bullet_image : 'Punktbilde',
position : 'Posisjon',
positioning_type : 'Type',
visibility : 'Synlighet',
zindex : 'Z-indeks',
overflow : 'Overflyt',
placement : 'Plassering',
clip : 'Klipp'
});
