// version 1.5.x $Id: nb.js 179 2007-02-14 19:24:38Z jens $
// author Joomla! i Norge http://www.joomlainorge.no oversettelser@joomlainorge.no
// copyright Copyright (C) 2005 - 2008 Joomla! i Norge. All rights reserved.
// license http://www.gnu.org/copyleft/gpl.html GNU/GPL, see LICENSE.php

tinyMCE.addToLang('table',{
general_tab : 'Generelt',
advanced_tab : 'Avansert',
general_props : 'Generelle egenskaper',
advanced_props : 'Avanserte egenskaper',
desc : 'Opprett/endre tabell',
row_before_desc : 'Opprett rad foran',
row_after_desc : 'Opprett rad etter',
delete_row_desc : 'Fjern rad',
col_before_desc : 'Opprett kolonne foran',
col_after_desc : 'Opprett kolonne etter',
delete_col_desc : 'Fjern kolonne',
rowtype : 'Rad i tabell',
title : 'Opprett/endre tabell',
width : 'Bredde',
height : 'Høyde',
cols : 'Kolonner',
rows : 'Rader',
cellspacing : 'Celle-mellomrom',
cellpadding : 'Celle-fylling',
border : 'Rammebredde',
align : 'Justering',
align_default : 'Ingen',
align_left : 'Venstre',
align_right : 'Høyre',
align_middle : 'Midtstilt',
row_title : 'tabellrad-egenskaper',
cell_title : 'tabellcelle-egenskaper',
cell_type : 'Celletype',
row_desc : 'tabellrad-egenskaper',
cell_desc : 'tabellcelle-egenskaper',
valign : 'Vertikal justering',
align_top : 'Topp',
align_bottom : 'Bunn',
props_desc : 'tabellegenskaper',
bordercolor : 'Rammefarge',
bgcolor : 'Bakgrunnsfarge',
merge_cells_title : 'Slå sammen tabellceller',
split_cells_desc : 'Splitt sammenslåtte tabellceller',
merge_cells_desc : 'Slå sammen tabellceller',
cut_row_desc : 'Fjern tabell rad',
copy_row_desc : 'Kopier tabell rad',
paste_row_before_desc : 'Lim inn tabell rad foran',
paste_row_after_desc : 'Lim inn tabell rad etter',
id : 'Id',
style: 'Stil',
langdir : 'Språkretning',
langcode : 'Språkkode',
mime : 'Målets MIME-type',
ltr : 'Venstre mot høyre',
rtl : 'Høyre mot venstre',
bgimage : 'Bakgrunnsbilde',
summary : 'Sum',
td : "Data",
th : "Overskrift",
cell_cell : 'Oppdater valgt celle',
cell_row : 'Oppdater alle celler i raden',
cell_all : 'Oppdater alle celler i tabellen',
row_row : 'Oppdater valgt rad',
row_odd : 'Oppdater ulike rader i tabellen',
row_even : 'Oppdater like rader i tabellen',
row_all : 'Oppdater alle rader i tabellen',
thead : 'Tabellhode',
tbody : 'Tabellkropp',
tfoot : 'Tabellfot',
del : 'Slett tabell',
scope : 'Hensikt',
row : 'Rad',
col : 'Kolonne',
rowgroup : 'Radgruppe',
colgroup : 'Kolonnegruppe',
col_limit : 'Du har overskredet maksimalt antall kolonner {$cols}.',
row_limit : 'Du har overskredet maksimalt antall rader {$rows}.',
cell_limit : 'Du har overskredet maktsimalt anatall celler {$cells}.',
missing_scope: 'Er du sikker på at du vil fortsette uten å oppgi hensikten med denne tabellens hodecelle?',
caption : 'Tabelltittel'
});