// version 1.5.x $Id: nb.js 179 2007-02-14 19:24:38Z jens $
// author Joomla! i Norge http://www.joomlainorge.no oversettelser@joomlainorge.no
// copyright Copyright (C) 2005 - 2008 Joomla! i Norge. All rights reserved.
// license http://www.gnu.org/copyleft/gpl.html GNU/GPL, see LICENSE.php

tinyMCE.addToLang('media',{
title : 'Sett inn / endre inkludert media',
desc : 'Sett inn / endre inkludert media',
general : 'Generelt',
advanced : 'Avansert',
file : 'Fil/nettadresse',
list : 'Liste',
size : 'Dimensjoner',
preview : 'Forhåndsvis',
constrain_proportions : 'Lås proporsjoner',
type : 'Type',
id : 'Id',
name : 'Navn',
class_name : 'Klasse',
vspace : 'V-Space',
hspace : 'H-Space',
play : 'Spill av automatisk',
loop : 'Løkke',
menu : 'Vis meny',
quality : 'Kvalitet',
scale : 'Skaler',
align : 'Juster',
salign : 'S-justering',
wmode : 'W-modues',
bgcolor : 'Bakgrunn',
base : 'Base',
flashvars : 'Flahs-variable',
liveconnect : 'SWLiveConnect',
autohref : 'AutoHREF',
cache : 'Mellomlagre',
hidden : 'Gjemt',
controller : 'Kontroller',
kioskmode : 'Kiosk-modus',
playeveryframe : 'Spill alle bilder',
targetcache : 'Mål for mellomlager',
correction : 'Ingen korreksjon',
enablejavascript : 'Aktiver JavaScript',
starttime : 'Start-tid',
endtime : 'Slutt-tid',
href : 'Href',
qtsrcchokespeed : 'Hold tilbake hastighet',
target : 'Mål',
volume : 'Volum',
autostart : 'Start automatisk',
enabled : 'Aktivert',
fullscreen : 'Fullskjerm',
invokeurls : 'Anrop nettadresser',
mute : 'Demp',
stretchtofit : 'Strekk til å passe inn',
windowlessvideo : 'Vindusløs video',
balance : 'Balanse',
baseurl : 'Basis-nettadresse',
captioningid : 'ID på undertekst',
currentmarker : 'Nåværende markør',
currentposition : 'Nåværende posisjon',
defaultframe : 'Standard ramme',
playcount : 'Antall ganger spilt',
rate : 'Hastighet',
uimode : 'UI-modus',
flash_options : 'Flash-valg',
qt_options : 'Quicktime-valg',
wmp_options : 'Windows media player-valg',
rmp_options : 'Real media player-valg',
shockwave_options : 'Shockwave-valg',
autogotourl : 'Automatisk gå til nettadresse',
center : 'Sentrer',
imagestatus : 'Bildestatus',
maintainaspect : 'Oppretthold sideforhold',
nojava : 'Ikke Java',
prefetch : 'Hent på forhånd(prefetch)',
shuffle : 'Stokk rekkefølge',
console : 'Konsoll',
numloop : 'Antall løkker',
controls : 'Kontroller',
scriptcallbacks : 'Script-callbacks',
swstretchstyle : 'Strekkstil',
swstretchhalign : 'Strekk H-justering',
swstretchvalign : 'Strekk V-justering',
sound : 'Lyd',
progress : 'Forløp',
qtsrc : 'QT-kilde',
qt_stream_warn : 'Strømmer fra rtsp-kilder skal legges feltet QT-kilde under avansert-fanen.\nDu må også legg til en ikke-direkteavspilt utgave i kilde-feltet..',
align_top : 'Topp',
align_right : 'Høyre',
align_bottom : 'Bunn',
align_left : 'Venstre',
align_center : 'Sentrer',
align_top_left : 'Topp venster',
align_top_right : 'Topp høyre',
align_bottom_left : 'Bunn venstre',
align_bottom_right : 'Bunn høyre'
});
